# Generated by Django 2.1 on 2018-08-18 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='biography')),
                ('image', models.ImageField(blank=True, null=True, upload_to=users.models.get_profile_image_path)),
                ('followers', models.ManyToManyField(related_name='user_followers', to='users.Profile')),
                ('followings', models.ManyToManyField(related_name='user_followings', to='users.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
