# Generated by Django 2.1 on 2018-09-05 10:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profile_photos/default.jpg', null=True, upload_to=accounts.models.get_profile_image_path, verbose_name='image'),
        ),
    ]
